/**
 * DTOs for Redis endpoints
 * Based on swagger-redis-create.json schemas
 */

/**
 * Input DTO for creating/updating Redis account data
 * All fields are optional to support progressive data collection across multiple screens
 */
export class RedAccountRedisInputDTO {
  idScreen?: string;
  minutsScreen?: number;
  fullName?: string;
  lastName?: string;
  motherLastName?: string;
  firstName?: string;
  birthDate?: string;
  civilStatus?: string;
  gender?: string;
  streetType?: string;
  streetName?: string;
  houseNumber?: string;
  department?: string;
  district?: string;
  province?: string;
  documentType?: string;
  documentNumber?: string;
  phoneNumber?: string;
  email?: string;
  isPeruvian?: string;
  acceptedPrivacyPolicy?: string;
  acceptedTermsAndConditions?: string;
  acceptedreadContract?: string;
  productId?: string;
  productName?: string;
  accountTypeId?: string;
  accountTypeName?: string;
  currency?: string;
  statusValOtp?: string;
  statusValZtrus?: string;
  pathImageDocumentFront?: string;
  pathImageDocumentReverse?: string;
  pathImagePersonSelfie?: string;
}

/**
 * Output DTO for Redis account data
 * Includes idTransaction which is generated by the system
 */
export class RedAccountDto {
  idScreen?: string | null;
  minutsScreen?: number;
  idTransaction?: string;
  fullName?: string | null;
  lastName?: string | null;
  motherLastName?: string | null;
  firstName?: string | null;
  birthDate?: string | null;
  civilStatus?: string | null;
  gender?: string | null;
  streetType?: string | null;
  streetName?: string | null;
  houseNumber?: string | null;
  department?: string | null;
  district?: string | null;
  province?: string | null;
  documentType?: string | null;
  documentNumber?: string | null;
  phoneNumber?: string | null;
  email?: string | null;
  isPeruvian?: string | null;
  acceptedPrivacyPolicy?: string | null;
  acceptedTermsAndConditions?: string | null;
  acceptedreadContract?: string | null;
  productId?: string | null;
  productName?: string | null;
  accountTypeId?: string | null;
  accountTypeName?: string | null;
  currency?: string | null;
  statusValOtp?: string | null;
  statusValZtrus?: string | null;
  pathImageDocumentFront?: string | null;
  pathImageDocumentReverse?: string | null;
  pathImagePersonSelfie?: string | null;
}

/**
 * Legacy DTO name for backward compatibility
 * @deprecated Use RedAccountRedisInputDTO instead
 */
export class RedAccountEntityDto extends RedAccountRedisInputDTO {}
